
#ifndef   SPECTRE_H_INCLUDED
#define   SPECTRE_H_INCLUDED

#define OFFSET  (1024)
#define ARRSIZE (256*4096)
#define BYTE_READ_REPEATS (150)
#define TARGET_SECTION (".SIDECHANNEL")

#define CONTROL_PORT (10001)
#define REQUEST_SIZE (50)

#endif // SPECTRE_H_INCLUDED

